apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: training-eks-Ep0xsk4Z
  region: us-east-2

nodeGroups:
  - name: ng
    desiredCapacity: 4
    minSize: 1
    maxSize: 4
    instanceType: t2.large
