groups:
- name: custom_prediction.rules
  rules:
   - alert: PredictionAlert
     expr: avg_over_time(mygauge [30s]) < 100000
     labels:
       severity: warning
     annotations:
       description: '{{$labels.kubernetes_pod_name}}: Average value is below the threshold ($100,000)! (current value is: {{ $value }})'
       summary: '{{$labels.instance}}: Average prediction is too low!'
           